webpack.optimize.UglifyJsPlugin is needless since webpack v4
```
Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
    at Object.get [as UglifyJsPlugin] (/Users/sue445/workspace/github.com/sue445/condo3/node_modules/webpack/lib/webpack.js:189:10)
    at Object.<anonymous> (/Users/sue445/workspace/github.com/sue445/condo3/webpack.config.js:83:30)
    at Module._compile (/Users/sue445/workspace/github.com/sue445/condo3/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
```